#!/usr/bin/env python
#-*- coding:utf-8 -*-

import sys
import os


class Main(object):
    def __init__(self, code):
        self.buf = [0]
        self.c = 0
        self.code = code
        self.ip = 0

    def _ptr_fwd(self):
        self.c += 1
        return
    
    def _ptr_bwd(self):
        self.c -= 1
        return

    def _ptr_access(self):
        while 1:
            if len(self.buf) > self.c:
                break
            self.buf.append(0)
        return
    
    def _ptr_inc(self):
        self._ptr_access()
        self.buf[self.c] += 1
        return
            
    def _ptr_dec(self):
        self._ptr_access()
        self.buf[self.c] -= 1
        return

    def _ptr_put(self):
        self._ptr_access()
        sys.stdout.write(chr(self.buf[self.c]))
        return

    def _ptr_get(self):
        self._ptr_access()
        self.buf[self.c] = ord(raw_input()[0])
        return

    def _while_start(self):
        self._ptr_access()
        if self.buf[self.c] == 0:
            self.ip += self.code[self.ip:].index("]") + 1
        return

    def _while_end(self):
        self.ip -= self.code[self.ip::-1].index("[")
        return

    def run(self):
        while self.ip < len(self.code):
            #print "IP:", self.ip
            c = self.code[self.ip]
            self.ip += 1
            if c == ">":
                self._ptr_fwd()
            elif c == "<":
                self._ptr_bwd()
            elif c == "+":
                self._ptr_inc()
            elif c == "-":
                self._ptr_dec()
            elif c == ".":
                self._ptr_put()
            elif c == ",":
                self._ptr_get()
            elif c == "[":
                self._while_start()
            elif c == "]":
                self._while_end()
            else:
                pass
        print

if __name__ == "__main__":
    if len(sys.argv) == 1:
        print "Usage:"
        print "%s [CODE or FILENAME]" % sys.argv[0]
        print
    else:
        if os.path.isfile(sys.argv[1]): # filename specified
            fd = open(sys.argv[1], "r")
            bf = Main(fd.read())
            fd.close()
            bf.run()
        else: # code specified
            bf = Main(sys.argv[1])
            bf.run()
